# fly.toml app configuration file generated for kuali-flycast-client on 2024-08-28T14:55:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kuali-flycast-client'
primary_region = 'sea'

[build]

[env]
FLYCAST_ORIGIN = 'http://kuali-flycast-server.flycast'

[[services]]
protocol = 'tcp'
internal_port = 8080
auto_stop_machines = "off"
auto_start_machines = false
min_machines_running = 0

[[services.ports]]
port = 80
handlers = ['http']

[services.concurrency]
type = 'requests'
soft_limit = 200

[[services.http_checks]]
interval = '15s'
timeout = '5s'
grace_period = '30s'
method = 'get'
path = '/healthz'
protocol = 'http'

[[vm]]
size = 'shared-cpu-1x'
